In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_colwidth', 200)

In [2]:
df = pd.read_csv('Ecommerce_Indonesia_21-Mar-2023_28-Mar-2023_Z3s0ZfZ2T4\Ecommerce_Indonesia_21-Mar-2023_28-Mar-2023_Z3s0ZfZ2T4_0.csv', on_bad_lines='skip', sep=';')

c:\Users\danendra\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (18,19,31,45,51,52,53,54,58,62,65,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,87,88,89,90,91,92,93,94,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,117,118,119,120,121,123,124,125,127,128,130,131,132,133,134,135,136,137,138,139,140,142,143,145,146,147,148,149,150,151,152,153,154,155,158,159,160,161,163,164,165,167,168,169,170,172,173,174,175,177,178,179,180,182,183,184,185,186,187,188,191,192,194,195,196,197,198,200,202,203,204,205,206,207,208,209,210,212,213,214,217,218,219,223,224,225,228,229,232,234,237,238,243,244,245,248,251,254,257,261,262,263,264,266,267,270,274,275,277,278,279,280,282,286,288,289,291,292,293,295,296,298,299,300,301,302,303,304,305,306,307,309,310,311,312,313,322,326,328,329,330,333,334,335,337,342,345,347,350,351,353,358,359,366,368,372,373,377,383,384,385,387,389,390,392,393,396,397,398,400,401,404,405,406,407,40

In [3]:
df.shape

(33638, 715)

In [6]:
for col in df.columns:
    if col.lower().startswith('pr'):
        print(col)

provinsi
project_id
product
produkdigital
produkall
propolis
proyektor
presto
promospesial
promo
produk
price


In [7]:
df['produk']

0        'Produk
1        'Produk
2        'Produk
3        'Produk
4        'Produk
          ...   
33633    'Produk
33634    'Produk
33635    'Produk
33636    'Produk
33637    'Produk
Name: produk, Length: 33638, dtype: object

In [8]:
post_detail = [
    'original_id',
    'date_created',
    'specific_type',
    'post_type',
    'object_name',
    'content',
    'final_sentiment',
    'lang',
    'content_type'
] 
post_stats = [
    'followers',
    'share',
    'like',
    'comment',
    'engagement',
    'reach',
    'impression',
    'engagement_rate'
]
labels = [
    'delivery',
    'customerservice',
    'website&apps',
    'payment',
    'price',
    'produk'
]
used_col = post_detail+post_stats+labels

In [9]:
df = df[used_col]

# Post Detail

In [10]:
df['specific_type'].value_counts()

'status     33145
'comment      211
'media        141
'video         88
'post          53
Name: specific_type, dtype: int64

In [11]:
df['post_type'].value_counts()

'talk         32809
'post_made      829
Name: post_type, dtype: int64

only use talk post_type karena yang post_made hanya balasan dari admin sehingga kemungkinan besar tidak mengandung sentimen

In [12]:
df[df['post_type']=="'talk"]['content'].sample(5)

8436     '@WerbenSteven @suiswap_app @tokopedia @mindblownnft Live Chat siap bantu keluhan transaksi kamu: Buka app DANA, pilih History/Riwayat,  pilih transaksi yg mau dilaporin dan pilih CHAT.
18129                                                'f Tisbury, in Martha’s Vineyard. A sho _USE_OUNASS_CODE_NAMSHI_COUPON_NOON_DISCOUNT_SIVVI_PROMO fortune upon the tur https://t.co/21DHGyVOYa
30102                                                'into the vidnet and O'Connor's set, wi _USE_OUNASS_CODE_NAMSHI_COUPON_NOON_DISCOUNT_SIVVI_PROMO rrative of those sin https://t.co/HYseaCFDae
31179                                                         'FUT Birthday promo on FIFA 23 is right around the corner. Could we see a FUT Birthday Icon Zinedine Zidane? https://t.co/IdxAfcpMAb
5004                                                                                                                             'Penarikan saldo dana di @tokopedia lama bangetttt, ga gercep -_-
Name: content, dtype: obj

In [13]:
df[df['post_type']=="'post_made"]['content'].sample(5)

12612                                                                                 '@bababloui Terkait kendalanya yuk Info nomor pesanan kamu melalui DM Twitter @ShopeeID untuk dibantu cek, stay safe 🙏 ^YP
4020     '@_babybrightvc Hai Lazadian, untuk gratis ongkir bisa didapatkan dengan mengumpulkan vouchernya di "Lucky Egg" ya. Kakak bisa cek ongkos kirim pesanan di bagian halaman produk yang mau dipesan. I...
9045     'Gak cuma baju baru, KENDARAAN BARU buat Lebaran nanti juga harus disiapin guys 😎😎   Mulai dari motor listrik sampai mobil, di #TokopediaGarage lagi pada diskon sampai 90% lhooo💸  Gasss, di sini 👇...
12996    '@Zayy_Zayy5119 Baik kak, mohon maaf ya buat kendalanya. Mimin infoin lg, tim Shopee yg menghubungi kakak dipastikan menggunakan no. tlp Indonesia dgn no. tlp +628 1500 702 / 1500 702. Boleh bantu...
3                                                                                                              'Halo ka yusuf.adrian21 . Baik, tunggu mimin meluncur

In [14]:
df['lang'].value_counts()

'en     22419
'in     10054
'es       131
'und      105
'tl        83
'pt        43
'fr        27
'qam       24
'th        21
'et        21
'qme       19
'ur        18
'ko        18
'tr        18
'de        16
'ht        14
'ro        12
'nl        10
'it        10
'pl        10
'ca         8
'fi         8
'da         8
'ja         8
'lt         6
'no         5
'cs         5
'hu         4
'hi         4
'ru         3
'eu         3
'cy         3
'qht        3
'ar         1
'is         1
'lv         1
'ta         1
Name: lang, dtype: int64

In [15]:
df[df['lang']=="'in"]['content'].sample(10)

11726    'Ngabuburit berhadiah yuk guys! ada voucher belanja Rp5 JUTA untuk 10 orang pemenang nih🥳  Langsung cek aja caranya di sini ya guys 👇  Semoga beruntung yah😉  #Bukalapak #DigodaPromoBukalapak #Buka...
4362     'Beli buku gak pake antri?! Kok bisa😱  Di #bigbadwolf kalian bisa tinggal pilih dan beli buku impor favorit kalian📚 Apalagi harganya mulai dari 10rb😝  Checkout sekarang dan dapetin diskon hingga 9...
3922                '@ms09850741 @suiswap_app @SuiMo_NFT @bukalapak @ovo_id Live Chat siap bantu keluhan transaksi kamu: Buka app DANA, pilih History/Riwayat,  pilih transaksi yg mau dilaporin dan pilih CHAT.
9088           'Coba cek ini, deh: "Ponds Bedak Wajah Bb Powder 50G - Face Powder Bedak Tabur" Rp25.398 di toko Unilever Mall Tokopedia. Bisa bebas ongkir, lho. https://t.co/7vV4kQdFRP https://t.co/ZrnYeycLVO
2593                                                           '🌟 Meja Lipat Lipat Portable 🌟  Rating : 4,5 Cek Diskon : https://t.co/L33ffUSwgE Gratis Ongkir : htt

In [16]:
df['post_type'].value_counts()

'talk         32809
'post_made      829
Name: post_type, dtype: int64

In [17]:
df['content_type'].value_counts()

'image     24196
'text       8607
'video       832
'others        3
Name: content_type, dtype: int64

In [18]:
df[df['content_type']=="'text"]['content'].sample(10)

5826     '@arpraaa_ @Kenzo_Ventures @wheatx_token @gopayindonesia @bukalapak Live Chat siap bantu keluhan transaksi kamu: Buka app DANA, pilih History/Riwayat,  pilih transaksi yg mau dilaporin dan pilih C...
3476                    'Makan ketoprak, sambil nonton sulap Belanja di Bukalapak, murahnya mantap!  Karena ada FLASH DEAL setiap hari dan juga diskon s.d. 90% lho buat kamu 😱😱😱  Cusss erbu langsung di sini 👇
24034                                                    'So Trish, Lita, and Becky will be on Miz TV. Surely Damage CTRL will show up there. I expect a promo battle with Miz as referee and then a big brawl 🔥
9551     'Hai, ready Netflix murahnya 1 bulan 32.000 (1p1u) sisa 4 19.000 (1p2u) sisa 3  Cepat 2 user satu profile di lock untuk dua orang , yang #zonauang yg jual bergaransi full promo canva wts wtb nct d...
3109                                                                                                                                         '@ayjmcity @sbtcon gamu

In [19]:
df[df['content_type']=="'image"]['content'].sample(10)

16453                                                         'omfortable quarters at the Bull. F _USE_OUNAS_CODE_ONASS_COUPON_TOYOU_NOON_DISCOUNT_ONAS_FORDEAL_PROMO down in the after- https://t.co/SOuRfem44M
348                               'Cek Pashmina Kaos Rayon Import Premium | Turkey Shawl | Pashmina Malaysia dengan harga Rp55.000. Dapatkan di Shopee sekarang! https://t.co/g1kdvDpOJw https://t.co/iwVJLc1Ra8
20193                                                          'Old Acton who is one of our count _USE_OUNAS_CODE_ONASS_COUPON_TOYOU_NOON_DISCOUNT_ONAS_FORDEAL_PROMO le. Like the great https://t.co/B5eDpUW9v0
6785                                                                                                                                                    '@tokopedia Tolong responnya min https://t.co/MHT9EaNBAt
15282                                                            'famous private agent lay aside al _USE_OUNAS_CODE_ONASS_COUPON_TOYOU_NOON_DISCOUNT_ONAS_FORDEAL_PR

In [20]:
#preprocess
clean_df = df[(df['post_type']=="'talk")& #karena yg post
                    (df['lang']=="'in")&
                    (df['content_type']=="'text")
                    ]

In [21]:
clean_df.shape

(4872, 23)

In [19]:
clean_df['content'].sample(10)

11274                     '@AirWolf_Shop @suiswap_app @bukalapak @tokopedia Live Chat siap bantu keluhan transaksi kamu: Buka app DANA, pilih History/Riwayat,  pilih transaksi yg mau dilaporin dan pilih CHAT.
8451                                   '@DafitZennzuka @NILE_WM @Telkomsel @tokopedia Yu ceritain keluhan kamu via DM, mohon informasikan juga ya nomor ticket kamu guna mempercepat penangangan... Terima Kasih
4717     '@_andhikk @ZkInferno @Agus_4217 @mak3lar @beerbahagialah @tokopedia Live Chat siap bantu keluhan transaksi kamu: Buka app DANA, pilih History/Riwayat,  pilih transaksi yg mau dilaporin dan pilih ...
11492                                                                      '@Widino @_xjaloe kita ada untuk kemasan yang 240gr harga 23rb termurah seindonesia bisa langsung dicheckout  https://t.co/qdZHgvJcNF
7786     'WOW! Kamu terpilih dapatin voucher belanja Cashback langsung Rp50.000, gunakan untuk belanja di Ramadan in Style! Sebarkan ke 5 temanmu dan dapatkan vouch

# Label

In [22]:
clean_df[labels].isnull().sum()/clean_df.shape[0]*100

delivery           84.236453
customerservice    85.857964
website&apps       94.622332
payment            48.932677
price              70.689655
produk              0.000000
dtype: float64

In [23]:
clean_df.shape[0] - clean_df[labels].isnull().sum()

delivery            768
customerservice     689
website&apps        262
payment            2488
price              1428
produk             4872
dtype: int64

In [24]:
clean_df[~clean_df['website&apps'].isnull()]['content']

108                                                                    'Dapatkan Rumah Impian anda dengan mengunjungi website kami https://t.co/uQ6MC6STg0 atau user OLX kami https://t.co/UoDLWJxm5O #JualRumah
113      'Masker Spirulina, SOLUSI tepat untuk km yang punya kendala kulit kusam, jerawat, flek, komedo, dll. INFO invite PIN 752110c8/Sms 089666535630, info lengkap cek disini https://t.co/YVFu6tIYgH via ...
115      'Masker Spirulina, SOLUSI tepat untuk km yang punya kendala kulit kusam, jerawat, flek, komedo, dll. INFO invite PIN 752110c8/Sms 089666535630, info lengkap cek disini https://t.co/YVFu6tIYgH via ...
119                                                                    'Dapatkan Rumah Impian anda dengan mengunjungi website kami https://t.co/uQ6MC6STg0 atau user OLX kami https://t.co/UoDLWJxm5O #JualRumah
121      'Masker Spirulina, SOLUSI tepat untuk km yang punya kendala kulit kusam, jerawat, flek, komedo, dll. INFO invite PIN 752110c8/Sms 089666535630, info lengka

In [25]:
clean_df.head()

original_id      date_created specific_type post_type  \
105  '1640363037382291456  27/03/2023 21.39       'status     'talk   
108  '1640328952853184512  27/03/2023 19.24       'status     'talk   
113  '1640276183039475713  27/03/2023 15.54       'status     'talk   
115  '1639898691900436480  26/03/2023 14.54       'status     'talk   
117  '1639824399602946049  26/03/2023 09.59       'status     'talk   

    object_name  \
105        'olx   
108        'olx   
113        'olx   
115        'olx   
117        'olx   

                                                                                                                                                                                                     content  \
105  '@glowinbeautyy @ssaiIormoon @frheyya @Askrlfess Dari kantorku yg pailit kak, karena gabisa bayar utang gaji karyawannya jadi ngelelang aset hrhe, tapi coba sambil ngulik2 kayak di olx gitu yg sec...   
108                                                                'Dapatkan Rumah Impian anda dengan mengunjungi website kami https://t.co/uQ6MC6STg0 atau user OLX kami https://t.co/UoDLWJxm5O #JualRumah   
113  'Masker Spirulina, SOLUSI tepat untuk km yang punya kendala kulit kusam, jerawat, flek, komedo, dll. INFO invite PIN 752110c8/Sms 089666535630, info lengkap cek disini https://t.co/YVFu6tIYgH via ...   
115  'Masker Spirulina, SOLUSI tepat untuk km yang punya kendala kulit kusam, jerawat, flek, komedo, dll. INFO invite PIN 752110c8/Sms 089666535630, info lengkap cek disini https://t.co/YVFu6tIYgH via ...   
117  '@pirrpear @sukaCOKLATbngt @worksfess Di tokped atau olx, sering cek aja kak , soal nya juga rejekiii rejekiii an , barang murah cepet laku , jadi kalo aku lagi nyari bisa tiap Hari aku pantengin ...   

    final_sentiment lang content_type  followers  ...  engagement  reach  \
105       'negative  'in        'text       1431  ...           1      0   
108       'positive  'in        'text        290  ...           0      0   
113       'positive  'in        'text       4514  ...           0      0   
115       'positive  'in        'text       4514  ...           0      0   
117       'negative  'in        'text          0  ...           0      0   

     impression  engagement_rate  delivery  customerservice   website&apps  \
105           0              0.0       NaN              NaN            NaN   
108           0              0.0       NaN              NaN  'Website&Apps   
113           0              0.0       NaN              NaN  'Website&Apps   
115           0              0.0       NaN              NaN  'Website&Apps   
117           0              0.0       NaN              NaN            NaN   

      payment   price   produk  
105  'Payment     NaN  'Produk  
108       NaN     NaN  'Produk  
113       NaN     NaN  'Produk  
115       NaN     NaN  'Produk  
117       NaN  'Price  'Produk  

[5 rows x 23 columns]

In [26]:
clean_df.to_csv('clean_df.csv', index=False)

# Untuk anotasi manual

In [27]:
import preprocessor as p
import numpy as np

In [28]:
clean_df = pd.read_csv('clean_df.csv')

In [29]:
used_col = ['original_id','content', 'final_sentiment'] + labels
clean_df = clean_df[used_col]
clean_df = clean_df.dropna(subset=['content'])
clean_df['clean_tweet'] = clean_df['content'].apply(p.clean)
clean_df = clean_df.reset_index(drop=True)

In [30]:
clean_df.shape[0] - clean_df[labels].isnull().sum()

delivery            768
customerservice     689
website&apps        262
payment            2488
price              1428
produk             4872
dtype: int64

In [31]:
clean_df

original_id  \
0     '1640363037382291456   
1     '1640328952853184512   
2     '1640276183039475713   
3     '1639898691900436480   
4     '1639824399602946049   
...                    ...   
4867  '1640139246412656640   
4868  '1640139208093503488   
4869  '1639117027045703683   
4870  '1638735573845426176   
4871  '1638366822704750592   

                                                                                                                                                                                                      content  \
0     '@glowinbeautyy @ssaiIormoon @frheyya @Askrlfess Dari kantorku yg pailit kak, karena gabisa bayar utang gaji karyawannya jadi ngelelang aset hrhe, tapi coba sambil ngulik2 kayak di olx gitu yg sec...   
1                                                                   'Dapatkan Rumah Impian anda dengan mengunjungi website kami https://t.co/uQ6MC6STg0 atau user OLX kami https://t.co/UoDLWJxm5O #JualRumah   
2     'Masker Spirulina, SOLUSI tepat untuk km yang punya kendala kulit kusam, jerawat, flek, komedo, dll. INFO invite PIN 752110c8/Sms 089666535630, info lengkap cek disini https://t.co/YVFu6tIYgH via ...   
3     'Masker Spirulina, SOLUSI tepat untuk km yang punya kendala kulit kusam, jerawat, flek, komedo, dll. INFO invite PIN 752110c8/Sms 089666535630, info lengkap cek disini https://t.co/YVFu6tIYgH via ...   
4     '@pirrpear @sukaCOKLATbngt @worksfess Di tokped atau olx, sering cek aja kak , soal nya juga rejekiii rejekiii an , barang murah cepet laku , jadi kalo aku lagi nyari bisa tiap Hari aku pantengin ...   
...                                                                                                                                                                                                       ...   
4867                                                                     'JIKA ADA YG INGIN DITANYAKAN BISA CHAT ADMIN DI DM/WA YA,   JANGAN LUPA FOLLOW INSTAGRAM KITA UNTUK UPDATE PROMO-PROMO MENDATANG🤩☝🏼   
4868                                                                                                                                                                       'tawarin kode promo zenius dong :(   
4869                                                                                                                                                                     'Mau Netflix yg lagi promo #zonauang   
4870                                                                                                                                                               'netflix 3 bulan yang lagi promo #zonauang   
4871                                                                                                                                                                'ada netflix yg lagi promo gak? #zonauang   

     final_sentiment delivery    customerservice   website&apps   payment  \
0          'negative      NaN                NaN            NaN  'Payment   
1          'positive      NaN                NaN  'Website&Apps       NaN   
2          'positive      NaN                NaN  'Website&Apps       NaN   
3          'positive      NaN                NaN  'Website&Apps       NaN   
4          'negative      NaN                NaN            NaN       NaN   
...              ...      ...                ...            ...       ...   
4867        'neutral      NaN  'Customer Service            NaN       NaN   
4868        'neutral      NaN                NaN            NaN       NaN   
4869        'neutral      NaN                NaN            NaN       NaN   
4870        'neutral      NaN                NaN            NaN       NaN   
4871       'negative      NaN                NaN            NaN       NaN   

       price   produk  \
0        NaN  'Produk   
1        NaN  'Produk   
2        NaN  'Produk   
3        NaN  'Produk   
4     'Price  'Produk   
...      ...      ...   
4867  'Price  'Produk   
4868  'Price  'Produ

In [32]:
clean_df['labels'] = ''
for i in range(len(clean_df)):
    label_concat = ''
    row = clean_df.iloc[i]
    for label in labels:
        if type(row[label])==str:
            label_concat+=f'{label}; '
    clean_df.at[i, 'labels'] = label_concat

In [33]:
clean_df

original_id  \
0     '1640363037382291456   
1     '1640328952853184512   
2     '1640276183039475713   
3     '1639898691900436480   
4     '1639824399602946049   
...                    ...   
4867  '1640139246412656640   
4868  '1640139208093503488   
4869  '1639117027045703683   
4870  '1638735573845426176   
4871  '1638366822704750592   

                                                                                                                                                                                                      content  \
0     '@glowinbeautyy @ssaiIormoon @frheyya @Askrlfess Dari kantorku yg pailit kak, karena gabisa bayar utang gaji karyawannya jadi ngelelang aset hrhe, tapi coba sambil ngulik2 kayak di olx gitu yg sec...   
1                                                                   'Dapatkan Rumah Impian anda dengan mengunjungi website kami https://t.co/uQ6MC6STg0 atau user OLX kami https://t.co/UoDLWJxm5O #JualRumah   
2     'Masker Spirulina, SOLUSI tepat untuk km yang punya kendala kulit kusam, jerawat, flek, komedo, dll. INFO invite PIN 752110c8/Sms 089666535630, info lengkap cek disini https://t.co/YVFu6tIYgH via ...   
3     'Masker Spirulina, SOLUSI tepat untuk km yang punya kendala kulit kusam, jerawat, flek, komedo, dll. INFO invite PIN 752110c8/Sms 089666535630, info lengkap cek disini https://t.co/YVFu6tIYgH via ...   
4     '@pirrpear @sukaCOKLATbngt @worksfess Di tokped atau olx, sering cek aja kak , soal nya juga rejekiii rejekiii an , barang murah cepet laku , jadi kalo aku lagi nyari bisa tiap Hari aku pantengin ...   
...                                                                                                                                                                                                       ...   
4867                                                                     'JIKA ADA YG INGIN DITANYAKAN BISA CHAT ADMIN DI DM/WA YA,   JANGAN LUPA FOLLOW INSTAGRAM KITA UNTUK UPDATE PROMO-PROMO MENDATANG🤩☝🏼   
4868                                                                                                                                                                       'tawarin kode promo zenius dong :(   
4869                                                                                                                                                                     'Mau Netflix yg lagi promo #zonauang   
4870                                                                                                                                                               'netflix 3 bulan yang lagi promo #zonauang   
4871                                                                                                                                                                'ada netflix yg lagi promo gak? #zonauang   

     final_sentiment delivery    customerservice   website&apps   payment  \
0          'negative      NaN                NaN            NaN  'Payment   
1          'positive      NaN                NaN  'Website&Apps       NaN   
2          'positive      NaN                NaN  'Website&Apps       NaN   
3          'positive      NaN                NaN  'Website&Apps       NaN   
4          'negative      NaN                NaN            NaN       NaN   
...              ...      ...                ...            ...       ...   
4867        'neutral      NaN  'Customer Service            NaN       NaN   
4868        'neutral      NaN                NaN            NaN       NaN   
4869        'neutral      NaN                NaN            NaN       NaN   
4870        'neutral      NaN                NaN            NaN       NaN   
4871       'negative      NaN                NaN            NaN       NaN   

       price   produk  \
0        NaN  'Produk   
1        NaN  'Produk   
2        NaN  'Produk   
3        NaN  'Produk   
4     'Price  'Produk   
...      ...      ...   
4867  'Price  'Produk   
4868  'Price  'Produ

In [34]:
clean_df.drop(columns=labels)[['original_id', 'content', 'clean_tweet', 'final_sentiment', 'labels']].to_csv('preprocessed.csv', index=False)

# Quadruplet zili anotation

In [11]:
import pandas as pd
from sklearn.model_selection import train_test_split
from experiments.src.utils import extract_quadruplet
from experiments.src.postprocessor import PostProcessor

In [6]:
df = pd.read_csv('Data/quadruplet/quadruplet_2200-data_annottated_clean.csv')
df.head()

content final_sentiment  \
0  @JUALAN_BASE @fleurlovincs Nder hpnya kamu pak...         neutral   
1  @teh_manis__ @ezash coba cari di olx mba kalo ...         neutral   
2  @tanyakanrl Kalo mau beli second jangan di tok...        positive   
3  kalo jam 1 malem gabisa tidur pengen makan nas...         neutral   
4  @tirta_cipeng Di luar dunia fashion, saya seri...         neutral   

   baseline_aspect_category  tweet_type  \
0         delivery; produk;  SUBJECTIVE   
1                   produk;  SUBJECTIVE   
2         delivery; produk;  SUBJECTIVE   
3  customerservice; produk;  SUBJECTIVE   
4                   produk;  SUBJECTIVE   

                                         clean_tweet  \
0   Nder hpnya kamu pake brp lama? Kayaknya jt ms...   
1   coba cari di olx mba kalo baru pertama kali m...   
2   Kalo mau beli second jangan di toko oren atau...   
3  kalo jam malem gabisa tidur pengen makan nasi ...   
4   Di luar dunia fashion, saya sering banget nem...   

                                          quadruplet  \
0       (hp, harga terlalu tinggi, negative, produk)   
1      (motor bekas, pertama kali, positive, produk)   
2  (beli second, biar lebih aman, negative, produ...   
3              (nasi goreng, enak, positive, produk)   
4         (olx, reseller, negative, customerservice)   

                                       triplet_label  
0               (hp, harga terlalu tinggi, negative)  
1              (motor bekas, pertama kali, positive)  
2  (beli second, biar lebih aman, negative);(olx,...  
3                      (nasi goreng, enak, positive)  
4                          (olx, reseller, negative)

In [5]:
df['len_clean_tweet'] = df['clean_tweet'].apply(lambda x:len(x.split()))

In [8]:
df['len_clean_tweet'].mean(), df['len_clean_tweet'].max()

(18.31679721496954, 58)

In [13]:
train, test = train_test_split(df, test_size=200, random_state=42)
val, test = train_test_split(test, test_size=100, random_state=42)

In [14]:
train.shape, test.shape, val.shape

((2098, 8), (100, 8), (100, 8))

In [15]:
train['len_clean_tweet'].mean(), train['len_clean_tweet'].max()

(18.17111534795043, 58)

In [17]:
train.to_csv('Data/quadruplet/quadruplet_2200-data_annottated_clean_train.csv', index=False)
test.to_csv('Data/quadruplet/quadruplet_2200-data_annottated_clean_test.csv', index=False)
val.to_csv('Data/quadruplet/quadruplet_2200-data_annottated_clean_val.csv', index=False)

## hitung category shopee

In [12]:
postprocessor = PostProcessor(use_postprocess=False)

In [21]:
shopee_cat = {
    'price':0,
    'produk':0,
    'website&apps':0,
    'payment':0,
    'delivery':0,
    'customerservice':0
}
sopi_idx = []
two_cat = 0
for i in range(len(df)):
    extractions = extract_quadruplet(df.iloc[i]['quadruplet'])
    if len(extractions)>1:
        two_cat+=1
    for quad in extractions:
        aspect, opinion, sentiment, aspect_cat = quad
        aspect, opinion, sentiment, aspect_cat = postprocessor.post_process(aspect, opinion, sentiment, aspect_cat, '')
        if aspect.lower()=='shopee':
            shopee_cat[aspect_cat]+=1
            sopi_idx.append(i)

In [22]:
two_cat

27

In [20]:
shopee_cat

{'price': 31,
 'produk': 268,
 'website&apps': 303,
 'payment': 28,
 'delivery': 123,
 'customerservice': 30}

In [19]:
df.iloc[sopi_idx]

content final_sentiment  \
71                               Shopee lagi kenapa deh        negative   
75                      gendeng bgt pagi2 bukany shopee        negative   
139   Ini shopee aku error atau gimana ya?? Tiap sea...        negative   
150   heran dah, bolak balek buat laporan paket yg b...        negative   
156   capek bgt keluhan gue cuma dianggap angin lewa...        negative   
...                                                 ...             ...   
2285                     masyaallah shopee kok lemot ya        positive   
2286  Iya woy, shopee ngide banget bikin diskon 100k...        negative   
2287  AJGGGG SHOPEE BARU DI REFRESH UDAH PADA HABIS ...        negative   
2291  @Dydydsha @discountfess itu bug nya kak, kalo ...         neutral   
2294  shopee gw doang apa emang lagi error sih. tiap...        negative   

             baseline_aspect_category  tweet_type  \
71                            produk;  SUBJECTIVE   
75                            produk;  SUBJECTIVE   
139                           produk;  SUBJECTIVE   
150                           produk;  SUBJECTIVE   
156                           produk;  SUBJECTIVE   
...                               ...         ...   
2285                   price; produk;  SUBJECTIVE   
2286  customerservice; price; produk;  SUBJECTIVE   
2287                delivery; produk;  SUBJECTIVE   
2291     website&apps; price; produk;  SUBJECTIVE   
2294                          produk;  SUBJECTIVE   

                                            clean_tweet  \
71                               Shopee lagi kenapa deh   
75                      gendeng bgt pagi2 bukany shopee   
139   Ini shopee aku error atau gimana ya?? Tiap sea...   
150   heran dah, bolak balek buat laporan paket yg b...   
156   capek bgt keluhan gue cuma dianggap angin lewa...   
...                                                 ...   
2285                     masyaallah shopee kok lemot ya   
2286  Iya woy, shopee ngide banget bikin diskon k ta...   
2287  AJGGGG SHOPEE BARU DI REFRESH UDAH PADA HABIS ...   
2291   itu bug nya kak, kalo kita refresh pihak shop...   
2294  shopee gw doang apa emang lagi error sih. tiap...   

                                             quadruplet  \
71    (shopee, lagi kenapa deh, negative, website&apps)   
75        (shopee, gendeng bgt, negative, website&apps)   
139   (shopee, error atau gimana ya?, negative, webs...   
150   (shopee, tbtb laporan selesai, negative, costu...   
156   (shopee, keluhan cuma dianggap angin lewat, ne...   
...                                                 ...   
2285     (shopee, kok lemot ya, negative, website&apps)   
2286  (shopee, diskon k tapi kuotanya dikit, negativ...   
2287  (shopee, di refresh udah pada habis semuaa, ne...   
2291  (shopee, nganggep kita pergi, negative, websit...   
2294       (shopee, lagi error, negative, website&apps)   

                                          triplet_label  
71                  (shopee, lagi kenapa deh, negative)  
75                      (shopee, gendeng bgt, negative)  
139           (shopee, error atau gimana ya?, negative)  
150            (shopee, tbtb laporan selesai, negative)  
156   (shopee, keluhan cuma dianggap angin lewat, ne...  
...                                                 ...  
2285                   (shopee, kok lemot ya, negative)  
2286   (shopee, diskon k tapi kuotanya dikit, negative)  
2287  (shopee, di refresh udah pada habis semuaa, ne...  
2291            (shopee, nganggep kita pergi, negative)  
2294                     (shopee, lagi error, negative)  

[783 rows x 7 columns]

In [16]:
shopee_cat

{'price': 31,
 'produk': 268,
 'website&apps': 303,
 'payment': 28,
 'delivery': 123,
 'customerservice': 30}

In [1]:
import pandas as pd

c:\Users\danendra\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
c:\Users\danendra\anaconda3\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
c:\Users\danendra\anaconda3\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [2]:
df = pd.read_csv('Data/quadruplet/quadruplet_1k_clean.csv')

In [6]:
df['len_tweet'] = df['clean_tweet'].apply(lambda x:len(x.split()))


In [7]:
df['len_tweet'].mean()

18.293

In [8]:
df['len_tweet'].max()

56

In [9]:
df['len_labels'] = df['postprocess_quad'].apply(lambda x:len(x.split()))

In [11]:
df['len_labels'].mean(), df['len_labels'].max()

(3.976, 16)

In [12]:
df['len_labels'].min()

1

# quintuplet data

In [12]:
from experiments.src.utils import extract_quintuplet
import pandas as pd

In [18]:
class Evaluator:
    def __init__(self):
        # == Metrics ==
        self.precision_fn = lambda n_tp, n_pred: float(n_tp) / float(n_pred) if n_pred != 0 else 0
        self.recall_fn = lambda n_tp, n_gold: float(n_tp) / float(n_gold) if n_gold != 0 else 0
        self.f1_fn = (
            lambda precision, recall: (2 * precision * recall) / (precision + recall)
            if precision != 0 or recall != 0
            else 0
        )
    def score(self, pred, gold):
        assert len(pred) == len(gold)
        n_tp, n_gold, n_pred = 0, 0, 0

        for i in range(len(pred)):
            n_gold += len(gold[i])
            n_pred += len(pred[i])

            for t in pred[i]:
                if t in gold[i]:
                    n_tp += 1
                
        precision = self.precision_fn(n_tp, n_pred)
        recall = self.recall_fn(n_tp, n_gold)
        f1 = self.f1_fn(precision, recall)
        return {"precision": precision, "recall": recall, "f1": f1}

In [19]:
evaluator = Evaluator()

In [2]:
df = pd.read_csv('Data/quadruplet/100_data_clean.csv')

In [3]:
all_entities = []
all_aspects = []
all_opinions = []
all_sentiments = []
all_categories = []
for i in range(len(df)):
    row = df.iloc[i]
    quintuplets = extract_quintuplet(row['label'])
    entities = []
    aspects = []
    opinions = []
    sentiments = []
    categories = []
    for quintuplet in quintuplets:
        entity, aspect_term, opinion_term, sentiment, aspect_category = quintuplet
        entities.append(entity)
        aspects.append(aspect_term)
        opinions.append(opinion_term)
        sentiments.append(sentiment)
        categories.append(aspect_category)
    all_entities.append(entity)
    all_aspects.append(aspect_term)
    all_opinions.append(opinion_term)
    all_sentiments.append(sentiment)
    all_categories.append(aspect_category)

In [4]:
test_df = pd.read_csv('Data/quadruplet/model_100-data_predictions.csv')

In [8]:
all_entities = []
all_aspects = []
all_opinions = []
all_sentiments = []
all_categories = []

all_entities_pred = []
all_aspects_pred = []
all_opinions_pred = []
all_sentiments_pred = []
all_categories_pred = []
for i in range(len(test_df)):
    row = test_df.iloc[i]
    #for true quintuplets
    true_quintuplets = extract_quintuplet(row['label'])
    entities = []
    aspects = []
    opinions = []
    sentiments = []
    categories = []
    for quintuplet in true_quintuplets:
        entity, aspect_term, opinion_term, sentiment, aspect_category = quintuplet
        entities.append(entity)
        aspects.append(aspect_term)
        opinions.append(opinion_term)
        sentiments.append(sentiment)
        categories.append(aspect_category)
    all_entities.append(entities)
    all_aspects.append(aspects)
    all_opinions.append(opinions)
    all_sentiments.append(sentiments)
    all_categories.append(categories)
    #for pred quintuplets
    pred_quintuplets = extract_quintuplet(row['p00_model_prediction'])
    entities_pred = []
    aspects_pred = []
    opinions_pred = []
    sentiments_pred = []
    categories_pred = []
    for quintuplet in pred_quintuplets:
        entity, aspect_term, opinion_term, sentiment, aspect_category = quintuplet
        entities_pred.append(entity)
        aspects_pred.append(aspect_term)
        opinions_pred.append(opinion_term)
        sentiments_pred.append(sentiment)
        categories_pred.append(aspect_category)
    all_entities_pred.append(entities_pred)
    all_aspects_pred.append(aspects_pred)
    all_opinions_pred.append(opinions_pred)
    all_sentiments_pred.append(sentiments_pred)
    all_categories_pred.append(categories_pred)

In [9]:
len(all_entities_pred), len(all_entities)

(10, 10)

In [35]:
evaluator.score(all_categories_pred, all_categories)

{'precision': 0.35714285714285715,
 'recall': 0.22727272727272727,
 'f1': 0.2777777777777778}

In [42]:
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.metrics import classification_report
from sklearn.metrics import multilabel_confusion_matrix, ConfusionMatrixDisplay

In [33]:
ASPECT_CATEGORIES = ['price', 'produk', 'website&apps', 'payment', 'delivery', 'customerservice', 'user']
mlb = MultiLabelBinarizer(classes=ASPECT_CATEGORIES)
y_true = mlb.fit_transform(all_categories)
y_pred = mlb.fit_transform(all_categories_pred)

c:\Users\danendra\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:895: UserWarning: unknown class(es) [''] will be ignored
  warnings.warn(


In [34]:
print(classification_report(y_true, y_pred, target_names=ASPECT_CATEGORIES))

                 precision    recall  f1-score   support

          price       0.00      0.00      0.00         0
         produk       0.33      1.00      0.50         1
   website&apps       0.50      1.00      0.67         2
        payment       0.00      0.00      0.00         2
       delivery       1.00      0.50      0.67         2
customerservice       0.00      0.00      0.00         0
           user       0.00      0.00      0.00         4

      micro avg       0.50      0.36      0.42        11
      macro avg       0.26      0.36      0.26        11
   weighted avg       0.30      0.36      0.29        11
    samples avg       0.40      0.40      0.40        11



c:\Users\danendra\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\danendra\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\danendra\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [50]:
cm = multilabel_confusion_matrix(y_true, y_pred)
for i, cat in enumerate(ASPECT_CATEGORIES):
    print(f'confusion matrix for {cat}')
    print(cm[i])

confusion matrix for price
[[10  0]
 [ 0  0]]
confusion matrix for produk
[[7 2]
 [0 1]]
confusion matrix for website&apps
[[6 2]
 [0 2]]
confusion matrix for payment
[[8 0]
 [2 0]]
confusion matrix for delivery
[[8 0]
 [1 1]]
confusion matrix for customerservice
[[10  0]
 [ 0  0]]
confusion matrix for user
[[6 0]
 [4 0]]


In [51]:
y_pred

array([[0, 0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0]])

In [52]:
y_true

array([[0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 0, 0]])